SELECT 
    COLUMN_NAME,
    DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'WorkoutPlans'
ORDER BY ORDINAL_POSITION;

SELECT 
    name
FROM sys.indexes
WHERE object_id = OBJECT_ID('dbo.WorkoutPlans');

SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Equipment'
ORDER BY ORDINAL_POSITION;