SELECT
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'WorkoutCompletions'
ORDER BY ORDINAL_POSITION;

SELECT OBJECT_ID('dbo.WorkoutCompletions') AS WorkoutCompletionsTable;